services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_recommender
    volumes:
      - C:/Users/Korisnik/Desktop/MovieRecommender/Movie-Recommender/postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dina.gladan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - db
  
  app:
    build:
      context: ../python-image
    volumes:
      - ../python-image:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/movie_recommender"
    working_dir: /app
    command: tail -f /dev/null


